version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
     - uploads_data:/app/uploads
     - db_data:/app/data
    environment:
      - PYTHONPATH=/app
      - RTSP_SERVER_HOST=rtsp-server
      - DATABASE_PATH=sqlite:///./data/videos.db
    depends_on:
      - rtsp-server
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
  rtsp-server:
    image: bluenviron/mediamtx
    ports:
      - "8554:8554"
      - "8888:8888"
    environment:
      - MTX_RTSPTRANSPORTS=tcp
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
  uploads_data: