version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
     - ./backend/uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
      - RTSP_SERVER_HOST=rtsp-server
    depends_on:
      - rtsp-server
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
  rtsp-server:
    image: bluenviron/mediamtx
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    environment:
      - MTX_RTSPTRANSPORTS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.x.x
    networks:
      - app-network
networks:
  app-network:
    driver: bridge